version: "3.9"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3.9.13-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
  consumer:
    container_name: "consumer"
    image: m99coder/rabbitmq-consumer:${CONSUMER_VERSION}-dev
    build:
      context: ./
      target: dev
    volumes:
      - .:/usr/src/app
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node consumer.mjs'
    environment:
      NODE_ENV: production
      AMQP_URL: amqp://rabbitmq:rabbitmq@rabbitmq:5672
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge
